name: Notify dependent repositories

on:
  push:
    branches: [ main ]

jobs:
  notify_models_package_repo_job:
    name: Notify odd-models-package repository
    runs-on: ubuntu-latest
    steps:
      - name: Notify package repository via GitHub REST API
        run: |
          curl \
          --request POST \
          --url https://api.github.com/repos/opendatadiscovery/odd-models-package/actions/workflows/6112466/dispatches \
          --header 'authorization: token ${{ secrets.OPENDATADISCOVERY_BOT_PAT }}' \
          --header 'content-type: application/json' \
          --data '{"ref": "main"}'

  notify_ingestion_contract_package_repo_job:
    name: Notify odd-platform-ingestion-contract repository
    runs-on: ubuntu-latest
    steps:
      - name: Notify package repository via GitHub REST API
        run: |
          curl \
          --request POST \
          --url https://api.github.com/repos/opendatadiscovery/opendatadiscovery-specification-contracts/actions/workflows/15836628/dispatches \
          --header 'authorization: token ${{ secrets.OPENDATADISCOVERY_BOT_PAT }}' \
          --header 'content-type: application/json' \
          --data '{"ref": "main"}'
