name: Notify PyPi contract package repository

on:
  push:
    branches: [ main ]

jobs:
  notify_contract_package_repo_job:
    name: Notify contract package repository
    runs-on: ubuntu-18.04
    steps:
      - name: Notify contract package repository via GitHub REST API
        run: |
          curl \
          --request POST \
          --url https://api.github.com/repos/opendatadiscovery/odd-contract-package/actions/workflows/6112466/dispatches \
          --header 'authorization: token ${{ secrets.OPENDATADISCOVERY_BOT_PAT }}' \
          --header 'content-type: application/json' \
          --data '{"ref": "main"}'

  notify_client_package_repo_job:
    name: Notify client package repository
    runs-on: ubuntu-18.04
    steps:
      - name: Notify client package repository via GitHub REST API
        run: |
          curl \
          --request POST \
          --url https://api.github.com/repos/opendatadiscovery/odd-client-package/actions/workflows/6160294/dispatches \
          --header 'authorization: token ${{ secrets.OPENDATADISCOVERY_BOT_PAT }}' \
          --header 'content-type: application/json' \
          --data '{"ref": "main"}'
